function R = registry(profile_id)
%WINDLIB.REGISTRY  Metadata for every wind profile in project 1.
%
%   R = windlib.registry()            all profiles, as a struct array
%   R = windlib.registry('wind03')    one profile
%   R = windlib.registry(3)           same, by menu number
%
% Fields:
%   id        'wind01'..'wind07'
%   num       original menu number in wind_profile_loader (1..7)
%   folder    output folder name used by the suite ('wind_profile_01')
%   name      human-readable label
%   T         duration in seconds
%   source    'csv' -> data/<id>.csv, or 'synthetic'
%   rescale   [] or [lo hi] target range
%   note      provenance
%
% Replaces the interactive menu in wind_profile_loader.m. The data itself
% now lives in +windlib/data/*.csv instead of ~950 lines of pasted coordinates.

    P = struct( ...
        'id',      {'wind01','wind02','wind03','wind04','wind05','wind06','wind07'}, ...
        'num',     {1, 2, 3, 4, 5, 6, 7}, ...
        'folder',  {'wind_profile_01','wind_profile_02','wind_profile_03', ...
                    'wind_profile_04','wind_profile_05','wind_profile_06','wind_profile_07'}, ...
        'name',    {'Original 12-24 m/s, 300 s', ...
                    'Small wind data, 60 s', ...
                    'Third small wind data, 60 s', ...
                    'Original rescaled to 10-15 m/s, 300 s', ...
                    'Synthetic 12 + sin(0.7t), 100 s', ...
                    'IEEE paper wind, 10 s', ...
                    'Renewable-Energy 2016, 100 s'}, ...
        'T',       {300, 60, 60, 300, 100, 10, 100}, ...
        'source',  {'csv','csv','csv','csv','synthetic','csv','csv'}, ...
        'csv',     {'wind01','wind02','wind03','wind01','', 'wind06','wind07'}, ...
        'rescale', {[], [], [], [10 15], [], [], []}, ...
        'note',    {'digitised, 61 source points -- heavily interpolated', ...
                    'digitised, 172 source points', ...
                    'digitised, 200 source points', ...
                    'same source as wind01, min-max rescaled', ...
                    'analytic, then movmean smoothed over 7 s', ...
                    'digitised, 166 source points -- only 10 s long, see windlib.feasibility', ...
                    'digitised, 244 source points'} );

    if nargin == 0 || isempty(profile_id)
        R = P;
        return;
    end

    if isnumeric(profile_id)
        hit = find([P.num] == profile_id, 1);
    else
        hit = find(strcmpi({P.id}, profile_id), 1);
        if isempty(hit)
            hit = find(strcmpi({P.folder}, profile_id), 1);
        end
    end

    if isempty(hit)
        error('windlib:registry:unknownProfile', ...
            'Unknown wind profile "%s". Valid ids: %s', ...
            num2str(profile_id), strjoin({P.id}, ', '));
    end
    R = P(hit);
end