function build_data(project_root, opts)
%REPORT.BUILD_DATA  Merge every profile's results into the bundle report.html reads.
%
%   report.build_data(project_root)
%   report.build_data(project_root, struct('verbose', false))
%
% Walks wind_profiles/manifest.json, pulls each profile's prediction summary
% and (if present) its control summary, and writes two files:
%
%   wind_profiles/report_data.json   for anything that wants to fetch() it
%   wind_profiles/report_data.js     assigns window.REPORT_DATA
%
% The .js twin is what makes report.html work when opened straight off disk:
% fetch() is blocked over file:// by CORS, a plain <script src> is not.
%
% WHY THIS IS ITS OWN FILE
%   It used to be a local function at the bottom of run_prediction_suite.m.
%   MATLAB scopes local functions to their file, so the control script's
%       if exist('build_report_data','file') == 2
%   was always false -- it silently skipped the refresh, and control results
%   never reached the report. Any caller can reach it now.

    if nargin < 2 || isempty(opts), opts = struct(); end
    if ~isfield(opts, 'verbose'), opts.verbose = true; end

    wp_dir = fullfile(project_root, 'wind_profiles');
    manifest_file = fullfile(wp_dir, 'manifest.json');

    if exist(manifest_file, 'file') ~= 2
        warning('report:build_data:noManifest', ...
            'No manifest at %s -- run a prediction first.', manifest_file);
        return;
    end

    manifest = local_read_json(manifest_file);
    profiles = manifest.profiles;
    if ~iscell(profiles)
        profiles = num2cell(profiles(:)');
    end

    bundle = struct();
    bundle.schema = 'wind-prediction-suite/report-data-1.1';
    bundle.generated_utc = char(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));

    entries = {};
    n_ctrl = 0;

    for k = 1:numel(profiles)
        p = profiles{k};

        summary_path = fullfile(wp_dir, p.id, 'report', 'prediction_suite_summary.json');
        if exist(summary_path, 'file') ~= 2
            if opts.verbose
                fprintf('  [skip] %s has no prediction summary yet\n', p.id);
            end
            continue;
        end

        e = struct();
        e.id      = p.id;
        e.name    = p.name;
        e.summary = local_read_json(summary_path);

        ctrl_path = fullfile(wp_dir, p.id, 'report', 'control_summary.json');
        if exist(ctrl_path, 'file') == 2
            try
                e.control = local_read_json(ctrl_path);
                n_ctrl = n_ctrl + 1;
            catch ME
                warning('report:build_data:badControl', ...
                    'control_summary.json for %s unreadable (%s) -- skipping it.', ...
                    p.id, ME.message);
            end
        end

        entries{end+1} = e; %#ok<AGROW>
    end

    bundle.profiles = entries;
    json_txt = jsonencode(bundle, 'PrettyPrint', true);

    json_out = fullfile(wp_dir, 'report_data.json');
    local_write(json_out, json_txt);

    js_out = fullfile(wp_dir, 'report_data.js');
    local_write(js_out, sprintf( ...
        '// Auto-generated by report.build_data. Do not edit.\nwindow.REPORT_DATA = %s;\n', json_txt));

    if opts.verbose
        fprintf('Report bundle: %d profile(s), %d with control results\n', numel(entries), n_ctrl);
        fprintf('  %s\n  %s\n', js_out, json_out);
    end
end

% =========================================================================
function S = local_read_json(f)
    fid = fopen(f, 'r');
    if fid == -1
        error('report:build_data:cannotRead', 'Cannot open %s', f);
    end
    raw = fread(fid, '*char')';
    fclose(fid);
    S = jsondecode(raw);
end

% =========================================================================
function local_write(f, txt)
    fid = fopen(f, 'w');
    if fid == -1
        error('report:build_data:cannotWrite', 'Cannot write %s', f);
    end
    % fwrite, not fprintf -- fprintf would interpret % and \ in the JSON
    fwrite(fid, txt, 'char');
    fclose(fid);
end
