function update_manifest(project_root, profile_id, summary_table, num_segments)
%REPORT.UPDATE_MANIFEST  Register a profile in wind_profiles/manifest.json.
%
%   report.update_manifest(project_root, profile_id, summary_table, num_segments)
%
% Entries are held in a CELL array, not a struct array. The original used
%     manifest.profiles = [manifest.profiles; entry];
% which throws the moment two entries have different field sets, and which
% encodes a lone entry as a JSON object rather than a one-element array.

    wp_dir = fullfile(project_root, 'wind_profiles');
    if ~exist(wp_dir, 'dir'), mkdir(wp_dir); end
    manifest_file = fullfile(wp_dir, 'manifest.json');

    existing = {};
    if exist(manifest_file, 'file') == 2
        try
            fid = fopen(manifest_file, 'r');
            raw = fread(fid, '*char')';
            fclose(fid);
            m = jsondecode(raw);
            if isfield(m, 'profiles') && ~isempty(m.profiles)
                if iscell(m.profiles)
                    existing = m.profiles(:)';
                else
                    existing = num2cell(m.profiles(:)');
                end
            end
        catch ME
            warning('report:update_manifest:unparseable', ...
                'manifest.json could not be parsed (%s) -- rebuilding it.', ME.message);
        end
    end

    % pretty name from any trailing digits, not a fixed two-character slice
    digits = regexp(profile_id, '\d+$', 'match', 'once');
    if isempty(digits)
        pretty = strrep(profile_id, '_', ' ');
    else
        pretty = sprintf('Wind Profile %s', digits);
    end

    [~, best_row] = min(summary_table.RMSE);

    entry = struct( ...
        'id',           profile_id, ...
        'name',         pretty, ...
        'description',  'Generated by run_prediction', ...
        'path',         ['wind_profiles/' profile_id], ...
        'summary',      'report/prediction_suite_summary.json', ...
        'report',       'report/prediction_suite_report.txt', ...
        'readme',       'README.md', ...
        'mat',          'prediction_suite_results.mat', ...
        'prediction',   'prediction/', ...
        'web',          'prediction/web/', ...
        'control',      'control/', ...
        'num_segments', num_segments, ...
        'num_models',   height(summary_table), ...
        'best_model',   summary_table.Model{best_row}, ...
        'best_rmse',    summary_table.RMSE(best_row), ...
        'updated_utc',  char(datetime('now', 'TimeZone', 'UTC', ...
                            'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z''')) );

    idx = [];
    for k = 1:numel(existing)
        if isfield(existing{k}, 'id') && strcmp(existing{k}.id, profile_id)
            idx = k; break;
        end
    end
    if isempty(idx)
        existing{end+1} = entry;
    else
        existing{idx} = entry;
    end

    % stable tab order in the report
    ids = cellfun(@(e) e.id, existing, 'UniformOutput', false);
    [~, order] = sort(ids);
    existing = existing(order);

    out.schema      = 'wind-prediction-suite/manifest-1.1';
    out.updated_utc = char(datetime('now', 'TimeZone', 'UTC', ...
                        'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));
    out.profiles    = existing;

    fid = fopen(manifest_file, 'w');
    fwrite(fid, jsonencode(out, 'PrettyPrint', true), 'char');
    fclose(fid);

    fprintf('Manifest updated: %d profile(s)\n', numel(existing));
end
